name: Update Apartment Data and GitHub Pages

# Controls when the action will run
on:
  schedule:
    # Runs at 00:00 every 3rd day
    - cron: '0 0 */3 * *'

  # Allows you to manually run the workflow from the Actions tab in GitHub
  workflow_dispatch:

jobs:
  update-data:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      # Step 4: Run the data extraction script
      - name: Run script to update data
        run: python script.py

      # Step 5: Commit and push the data.json and index.html to GitHub Pages
      - name: Commit and push changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "GitHub Actions"
          git add ./data/data.json
          git add index.html
          git commit -m "Update data.json and regenerate index.html"
          git push origin main

      # Step 6: Deploy to GitHub Pages (if you are using gh-pages branch)
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
