name: Update and Deploy to GitHub Pages

on:
  # Runs at 00:00 every 3rd day
  schedule:
    - cron: '0 0 */3 * *'

  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to manually run the workflow from the Actions tab in GitHub
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  update-and-deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Download the latest data.json file from the repository
      - name: Download data.json
        run: |
          curl -o ./data/minto_data.json https://raw.githubusercontent.com/Yin-Marina/apartment_tracker/main/data/minto_data.json
          curl -o ./data/fleming_data.json https://raw.githubusercontent.com/Yin-Marina/apartment_tracker/main/data/fleming_data.json
          curl -o ./data/jb_data.json https://raw.githubusercontent.com/Yin-Marina/apartment_tracker/main/data/jb_data.json
      # Step 3: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      # Step 4: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4

      # Step 5: Run the data extraction script
      - name: Run script to update data
        run: python script.py

      # Step 6: Commit and push the data.json and index.html to GitHub
      - name: Commit and push changes
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          git remote set-url origin https://$PAT_TOKEN@github.com/Yin-Marina/apartment_tracker.git
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "GitHub Actions"
          git add ./data/minto_data.json
          git add ./data/fleming_data.json
          git add ./data/jb_data.json
          git commit -m "Update data.json"
          git push origin HEAD:main
